### ISSUE TITLE
Call stack on fresh pip install of firex-flame

### ISSUE THREAD

**Issue by MarcDelahousse** [FireXStuff/firex-flame#3]
Not getting anything on my fresh install on my home PC

127.0.0.1 - - [31/Jul/2019 22:49:01] "GET /ui/js/app.dd6ad85f.js.map HTTP/1.1" 404 365 0.000869
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/marc/PycharmProjects/firex/venv/lib/python3.5/site-packages/firex_flame/event_broker_processor.py", line 67, in run
    self._run_from_broker()
  File "/home/marc/PycharmProjects/firex/venv/lib/python3.5/site-packages/firex_flame/event_broker_processor.py", line 76, in _run_from_broker
    self.flame_controller.dump_complete_data_model(self.event_aggregator)
  File "/home/marc/PycharmProjects/firex/venv/lib/python3.5/site-packages/firex_flame/controller.py", line 28, in dump_complete_data_model
    self.model_dumper.dump_aggregator_complete_data_model(event_aggregator, self.run_metadata)
  File "/home/marc/PycharmProjects/firex/venv/lib/python3.5/site-packages/firex_flame/model_dumper.py", line 96, in dump_aggregator_complete_data_model
    self.dump_complete_data_model(event_aggregator.tasks_by_uuid, event_aggregator.root_uuid, run_metadata)
  File "/home/marc/PycharmProjects/firex/venv/lib/python3.5/site-packages/firex_flame/model_dumper.py", line 103, in dump_complete_data_model
    lambda t: t['task_num'])
TypeError: unorderable types: function() < list()

**Comment by djungic** [comment]
The symptom is addressed in 346f29b8f7d, but I'm wondering how the run got to model dumping without encountering a root task. 

What chain was being executed?
